<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQaxQYR8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQaxQYR8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQaxQYR8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQaxQYR8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQaxQYR8\App_KernelDevDebugContainer([
    'container.build_hash' => 'QaxQYR8',
    'container.build_id' => 'f9ee312b',
    'container.build_time' => 1629829918,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQaxQYR8');
