<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'api_post_show' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], []],
    'login_page' => [[], ['_controller' => 'App\\Controller\\UserLoginController::loginPage'], [], [['text', '/login']], [], []],
    'login_form_post' => [[], ['_controller' => 'App\\Controller\\UserLoginController::loginUser'], [], [['text', '/login']], [], []],
    'register_page' => [[], ['_controller' => 'App\\Controller\\UserLoginController::registerPage'], [], [['text', '/register']], [], []],
    'register_post' => [[], ['_controller' => 'App\\Controller\\UserLoginController::registerUser'], [], [['text', '/register']], [], []],
    'user_tasks_page' => [[], ['_controller' => 'App\\Controller\\TaskController::tasksListPage'], [], [['text', '/tasks']], [], []],
    'new_task_page' => [[], ['_controller' => 'App\\Controller\\TaskController::newTaskPage'], [], [['text', '/new_task']], [], []],
    'new_task_post' => [[], ['_controller' => 'App\\Controller\\TaskController::createNewTask'], [], [['text', '/new_task']], [], []],
    'tasks_csv' => [[], ['_controller' => 'App\\Controller\\TaskController::generateCsvFile'], [], [['text', '/tasks.csv']], [], []],
];
